[subtasks.ornament_extraction]
name = "饰品提取"
func = "ornament_extraction"
cost = 40
max_count = 6
levels = ["西风丛中", "月下朱殷", "纷争不休",
    "蠹役饥肠", "永恒笑剧", "伴你入眠",
    "天剑如雨", "孽果盘生", "百年冻土",
    "温柔话语", "浴火钢心", "坚城不倒"]
results = ["永恒之地翁法罗斯/天国@直播间", "妖精织梦的乐园/沉欢醉饮的海隅", "谧宁拾骨地/渊思寂虑的巨树",
    "沉陆海域露莎卡/奇想蕉乐园", "奔狼的都蓝王朝/劫火莲灯铸炼宫", "无主荒星茨冈尼亚/出云显世与高天神国",
    "苍穹战线格拉默/梦想之地匹诺康尼", "繁星竞技场/折断的龙骨", "筑城者的贝洛伯格/停转的萨尔索图",
    "泛银河商业公司/星体差分机", "盗贼公国塔利亚/生命的翁瓦克", "太空封印站/不老者的仙舟"]

[subtasks.calyx_golden]
name = "拟造花萼（金）"
func = "calyx_golden"
cost = 10
max_count = 24
levels = [
    "回忆之蕾（二相乐园）",
    "以太之蕾（二相乐园）",
    "珍藏之蕾（二相乐园）",
    "回忆之蕾（翁法罗斯）",
    "以太之蕾（翁法罗斯）",
    "珍藏之蕾（翁法罗斯）",
    "回忆之蕾（匹诺康尼）",
    "以太之蕾（匹诺康尼）",
    "珍藏之蕾（匹诺康尼）",
    "回忆之蕾（仙舟罗浮）",
    "以太之蕾（仙舟罗浮）",
    "珍藏之蕾（仙舟罗浮）",
    "回忆之蕾（雅利洛VI）",
    "以太之蕾（雅利洛VI）",
    "珍藏之蕾（雅利洛VI）"]

[subtasks.calyx_crimson]
name = "拟造花萼（赤）"
func = "calyx_crimson"
cost = 10
max_count = 24
results = [
    "月狂獠牙", "净世残刃",
    "神体琥珀", "琥珀的坚守",
    "天谴血矛", "逆时一击", "逐星之矢",
    "万相果实", "永恒之花",
    "精致色稿", "智识之钥",
    "天外乐章", "群星乐章",
    "焚天之魔", "沉沦黑曜",
    "阿赖耶华",
    "《绒绒号》典藏版合集"]

[subtasks.stagnant_shadow]
name = "凝滞虚影"
func = "stagnant_shadow"
cost = 30
max_count = 8
results = [
    "侵略凝块", "星际和平工作证", "幽府通令", "铁狼碎齿",
    "明辉日珥", "忿火之心", "过热钢刃", "恒温晶壳",
    "海妖残鰭", "冷藏梦箱", "苦寒晶壳", "风雪之角",
    "狂雷扫弦","兽棺之钉", "炼形者雷枝", "往日之影的雷冠",
    "暮辉烬蕾", "一杯酪酊的时代", "无人遗垢", "暴风之眼",
    "暗帷月华", "炙梦喷枪", "苍猿之钉", "虚幻铸铁",
    "纷争前兆", "一曲合弦的幻景", "镇灵敕符", "往日之影的金饰"]
levels = [
    "溟簇之形", '职司之形', '幽府之形', '锋芒之形',
    "残灰之形", "嗔怒之形", '燔灼之形', '炎华之形',
    "塞壬之形", '冰酿之形', '冰棱之形', '霜晶之形',
    "音爆之形", "机狼之形", '震厄之形', '鸣雷之形',
    '烬日之形', '今宵之形', '天人之形', '巽风之形',
    '凛月之形', '焦炙之形', '孽兽之形', '空海之形',
    '役轮之形', '弦音之形', '偃偶之形', '幻光之形']

[subtasks.caver_of_corrosion]
name = "侵蚀隧洞"
func = "caver_of_corrosion"
cost = 40
max_count = 6
results = [
    "闪耀功勋的魔法少女/应天涉远的卜者",
    "再创天地的救世主/自匿星芒的隐士", "烈阳惊雷的女武神/恶海逐波的船长", "凯歌祝捷的英豪/哀歌覆国的诗人",
    "重循苦旅的司铎/识海迷坠的学者", "荡除蠹灾的铁骑/风举云飞的勇烈", "死水深潜的先驱/机心戏梦的钟表匠",
    "毁烬焚骨的大公/幽锁深牢的系囚", "宝命长存的莳者/骇域漫游的信使", "熔岩锻铸的火匠/盗匪荒漠的废土客",
    "净庭教宗的圣骑士/激奏雷电的乐队", "戍卫风雪的铁卫/繁星璀璨的天才", "云无留迹的过客/野穗伴行的快枪手",
    "街头出身的拳王/流星追迹的怪盗", "密林卧雪的猎人/晨昏交界的翔鹰"]
levels = [
    "魔占之径",
    "隐救之径", "雳勇之径", "弦歌之径",
    "迷识之径", "勇骑之径", "梦潜之径",
    "幽冥之径", "药使之径", "野焰之径",
    "圣颂之径", "睿智之径", "漂泊之径",
    "迅拳之径", "霜风之径"]

[subtasks.echo_of_war]
name = "历战余响"
func = "echo_of_war"
cost = 30
max_count = 3
results = ["灭流绝溢的默", "阳雷的遥想", "吉光片羽", "同愿的遗音", "蛀星孕灾的旧恶", "无穷假身的遗恨", "守护者的悲愿", "毁灭者的末路"]