[[tasks]]
name = "启动游戏"
main = "StartGameTask"
module = "tasks.StartGameTask"

[[tasks]]
name = "清开拓力"
main = "TrailblazePowerTask"
module = "tasks.TrailblazePowerTask"

[[tasks]]
name = "领取奖励"
main = "ReceiveRewardsTask"
module = "tasks.ReceiveRewardsTask"

[[tasks]]
name = "旷宇纷争"
main = "CosmicStrifeTask"
module = "tasks.CosmicStrifeTask"

[[tasks]]
name = "任务完成"
main = "MissionAccomplishTask"
module = "tasks.MissionAccomplishTask"

[websockets]
package = "websockets"
host = "0.0.0.0"
port = 8765